[project]
name = "text-ssl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aletheiaaaaa", email = "carbon674@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=5.0.1",
    "pyyaml>=6.0.3",
    "torch>=2.13.0",
    "torchao>=0.18.0",
    "transformers>=5.14.1",
    "wandb>=0.30.0",
]

[project.scripts]
text-ssl = "text_ssl:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
